version: "3.9"

x-php-variables: &php-environment
  environment:
    - APP_ENV=dev
    - ACCESS_TOKENS=${ACCESS_TOKENS:-token123}

services:
  reverse-proxy:
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$05$$A9hvJPnfOr3r7BsKdjwPn.SGKElp6L13ZlWumcXgO47NADt78sfZi"
    volumes:
      - ./docker/traefik/dev/letsencrypt:/letsencrypt
      - ./docker/traefik/dev/traefik.yaml:/etc/traefik/traefik.yaml
  
  php:
    <<: *php-environment

  database:
    ports:
      - "64067:5432"
      
  web:
    labels:
      - "traefik.http.routers.webapi.rule=Host(`achievernotifier.docker.localhost`) && (PathPrefix(`/api/v1`) || PathPrefix(`/.well-known/acme-challenge/`))"
    volumes:
      - ./docker/traefik/dev/letsencrypt:/var/www/letsencrypt
      
  whoami:
    container_name: ${APP_NAME:-achievernotifier}-test-whoami
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    networks:
      - reverse_proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web,websecure"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
      
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
