version: "3.9"

x-php-variables: &php-environment
  environment:
    - APP_ENV=prod
    - ACCESS_TOKENS=${ACCESS_TOKENS:-token123}

services:
  php:
    env_file:
      - .env
    restart: always
    <<: *php-environment

  web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.achievernotifier-api.rule=Host(`server1591.server-vps.com`) && PathPrefix(`/api/v1`)"
      
  database:
    env_file:
      - .env
    expose:
      - 5432
    restart: always

  reverse-proxy:
    restart: always
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
