version: "3.9"

x-php-variables: &php-environment
  environment:
    - APP_ENV=prod
    - ACCESS_TOKENS=${ACCESS_TOKENS:-token123}

services:
  reverse-proxy:
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`proxy.leogiftbox.com`)"
      - "traefik.http.middlewares.auth.basicauth.users=authuser:$$2y$$05$$cr2.VRJTg6AWHMWiFHIU..7rlHFGTVzTkcMBIjNWNFcF9jMjbKwgq"
    volumes:
      - ./docker/traefik/prod/letsencrypt:/letsencrypt
      - ./docker/traefik/prod/traefik.yaml:/etc/traefik/traefik.yaml
  
  php:
    env_file:
      - .env
    restart: always
    <<: *php-environment
      
  database:
    env_file:
      - .env
    restart: always

  web:
    labels:
      - "traefik.http.routers.achievernotifier-api.rule=(Host(`194.33.180.50`) || Host(`leogiftbox.com`) ) && PathPrefix(`/api/v1`)"
    
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
