version: "3.9"

x-php-variables: &php-environment
  environment:
    - APP_ENV=${APP_ENV:-dev}
    - ACCESS_TOKENS=${ACCESS_TOKENS:-token123}

services:
  php:
    container_name: ${APP_NAME:-an}-php
    build:
        context: .
        dockerfile: ./Dockerfile
        target: php_base
    networks:
      - reverse_proxy_network
      - default
    depends_on:
      - database
    labels:
      - "traefik.enable=false"
    volumes:
      - ./app:/app:rw
    <<: *php-environment

###> doctrine/doctrine-bundle ###
  database:
    container_name: ${APP_NAME:-an}-db
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    networks:
      - default
    labels:
      - "traefik.enable=false"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  web:
    container_name: ${APP_NAME:-an}-server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: nginx_server
    networks:
      - reverse_proxy_network
      - default
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapi-http.entrypoints=web"
      - "traefik.http.routers.webapi-http.middlewares=webapi-https"
      - "traefik.http.middlewares.webapi-https.redirectscheme.scheme=https"
      - "traefik.http.routers.webapi.entrypoints=websecure"
      - "traefik.http.routers.webapi.tls=true"
    volumes:
      - ./public:/app/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/.well-known/pki-validation:/var/www/.well-known/pki-validation
      - ./tmp/log/nginx/:/var/log/nginx

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  reverse_proxy_network:
    external: true
