version: "3.9"

x-php-variables: &php-environment
  environment:
    - APP_ENV=${APP_ENV:-prod}
    - ACCESS_TOKENS=${ACCESS_TOKENS:-token123}
    - DATABASE_URL=postgresql://app_user:!ChangeMe!@database:5432/app_db?serverVersion=15&charset=utf8
    
services:
  reverse-proxy:
    container_name: ${APP_NAME:-an}-reverse-proxy-${APP_ENV:-prod}
    restart: always
    labels:
      - "traefik.http.routers.api.rule=Host(`proxy.achievernotifier.com`) || Host(`traefik.docker.prod.localhost`)"
      - "traefik.http.middlewares.auth.basicauth.users=authuser:$$2y$$05$$cr2.VRJTg6AWHMWiFHIU..7rlHFGTVzTkcMBIjNWNFcF9jMjbKwgq"
    volumes:
      - ./docker/traefik/prod/configuration:/etc/traefik
      - ./docker/traefik/prod/cert:/etc/traefik/cert
  
  php:
    container_name: ${APP_NAME:-an}-php-${APP_ENV:-prod}
    restart: always
    env_file:
      - .env.prod
    <<: *php-environment
      
  database:
    container_name: ${APP_NAME:-an}-db-${APP_ENV:-prod}
    restart: always
    ports:
      - "64068:5432"

  web:
    container_name: ${APP_NAME:-an}-server-${APP_ENV:-prod}
    restart: always
    labels:
      - "traefik.http.routers.webapi-http.rule=(Host(`achievernotifier.com`) || Host(`achievernotifier.docker.prod.localhost`)) && PathPrefix(`/api/v1`, `/.well-known`, `/ishealthy`)"
      - "traefik.http.routers.webapi.rule=(Host(`achievernotifier.com`) || Host(`achievernotifier.docker.prod.localhost`)) && PathPrefix(`/api/v1`, `/.well-known`, `/ishealthy`)"
      - "traefik.http.routers.webapi.tls=true"
      - "traefik.http.routers.webapi.tls.domains[0].main=achievernotifier.com"
    
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
