version: "3.9"

x-php-variables: &php-environment
  environment:
    - APP_ENV=prod
    - ACCESS_TOKENS=${ACCESS_TOKENS:-token123}

services:
  app:
    <<: *php-environment

  traefik:
    container_name: traefik
    image: traefik:alpine
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: unless_stopped
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
