version: "3.9"

services:
  reverse-proxy:
    container_name: ${APP_NAME:-an}-reverse-proxy-${APP_ENV:-prod}
    restart: always
    labels:
      - "traefik.http.routers.api.rule=Host(`proxy.achievernotifier.com`) || Host(`traefik.docker.${APP_ENV:-prod}.local`)"
      - "traefik.http.middlewares.auth.basicauth.users=authuser:$$2y$$05$$cr2.VRJTg6AWHMWiFHIU..7rlHFGTVzTkcMBIjNWNFcF9jMjbKwgq"
    volumes:
      - ./docker/traefik/prod/letsencrypt:/letsencrypt
      - ./docker/traefik/prod/configuration:/etc/traefik
      - ./docker/certificates/*.crt:/etc/traefik/*.crt
      - ./docker/certificates/*.key:/etc/traefik/*.key
  
  php:
    container_name: ${APP_NAME:-an}-php-${APP_ENV:-prod}
    restart: always
      
  database:
    container_name: ${APP_NAME:-an}-db-${APP_ENV:-prod}
    restart: always
    ports:
      - "64068:5432"

  web:
    image: ${APP_NAME:-an}-server:${APP_ENV:-prod}
    restart: always
    labels:
      - "traefik.http.routers.webapi-http.rule=Host(`achievernotifier.com`) && PathPrefix(`/api/v1`, `/.well-known`, `/ishealthy`)"
      - "traefik.http.routers.webapi.rule=Host(`achievernotifier.com`) && PathPrefix(`/api/v1`, `/.well-known`, `/ishealthy`)"
      - "traefik.http.routers.webapi.tls=true"
    
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
