version: "3.9"

x-php-variables: &php-environment
  environment:
    - APP_ENV=${APP_ENV:-dev}
    - ACCESS_TOKENS=${ACCESS_TOKENS:-token123}

services:
  php:
    container_name: ${APP_NAME:-achievernotifier}-php
    build:
        context: .
        dockerfile: ./Dockerfile
        target: php_base
    env_file:
      - .env
    networks:
      - reverse_proxy_network
      - default
    depends_on:
      - database
    volumes:
      - ./app:/app:rw
    <<: *php-environment

###> doctrine/doctrine-bundle ###
  database:
    container_name: ${APP_NAME:-achievernotifier}-db
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    env_file:
      - .env
    networks:
      - default
    labels:
        com.symfony.server.service-prefix: 'DATABASE'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  web:
    container_name: ${APP_NAME:-achievernotifier}-server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: nginx_server
    networks:
      - reverse_proxy_network
      - default
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.achievernotifier-api.rule=Host(`achievernotifier.localhost`) && PathPrefix(`/api/v1`)"
#       - "traefik.http.routers.achievernotifier-api.tls=true"
#       - "traefik.http.routers.achievernotifier-api.tls.certresolver=letsencrypt"
#       - "traefik.http.routers.achievernotifier-api.service=achievernotifier-api-service"
#       - "traefik.http.services.achievernotifier-api-service.loadbalancer.server.scheme=https"
#       - "traefik.http.services.achievernotifier-api-service.loadbalancer.server.port=80"
    volumes:
      - ./public:/app/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./tmp/log/nginx/:/var/log/nginx

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  reverse_proxy_network:
    external: true
