version: "3.9"

services:
  reverse-proxy:
    container_name: ${APP_NAME:-achievernotifier}-reverse-proxy
    build:
      context: .
      dockerfile: ./Dockerfile
      target: reverse_proxy
    networks:
      - reverse_proxy_network
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.routers.api.entrypoints=web,websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  reverse_proxy_network:
    external: true
