# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    google_application_credentials: '%env(resolve:GOOGLE_AUTH_CONFIG)%'
    web_host: '%env(WEB_HOST)%'
    table_prefix: 'smfn_'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            'string $projectDir': '%kernel.project_dir%'
            'string $projectEnvironment': '%kernel.environment%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Security/JWTTokenAuthenticator.php'

    DataFixtures\:
        resource: '../fixtures'
        
    App\Event\Listener\TablePrefixListener:
        arguments:
            - '%table_prefix%'
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, method: loadClassMetadata }
            
    App\ValueResolver\JsonTransferValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }
    
    Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer:
         class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
         tags: [serializer.normalizer]  

    api.custom_jwt_authenticator:
        class: App\Security\JWTTokenAuthenticator
        parent: lexik_jwt_authentication.security.jwt_authenticator
