defaultEntryPoints = ["http", "https"]

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]
[entryPoints.api]
address = ":8000"

[api]
entryPoint = "api"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "server1591.server-vps.com"
exposedByDefault = false

[acme]
email = "admin@server1591.server-vps.com"
entryPoint = "https"
storage = "/etc/traefik/acme/acme.json"
onHostRule = true
