providers:
  docker:
    network: reverse_proxy_network
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    httpClientTimeout: 300
    
api: {}
  
entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
