providers:
  docker:
    network: reverse_proxy_network
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    httpClientTimeout: 300
    
api: {}
  
entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

tls:
  options:
    default:
      clientAuth:
        # in PEM format. each file can contain multiple CAs.
        caFiles:
#           - /cert/x509.crt
#           - /cert/intermediate.crt
          - /cert/root.crt
        clientAuthType: RequireAndVerifyClientCert
