providers:
  docker:
    network: reverse_proxy_network
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    httpClientTimeout: 300
    
api: {}
  
entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

tls:
  certificates:
    - certFile: /cert/achievernotifier.com_intermediate.cer
      keyFile: /cert/achievernotifier.com_618396088AD1C05A311618D11165503E.cer
