providers:
  docker:
    network: reverse_proxy_network
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    httpClientTimeout: 300
    
api: {}

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@localhost.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

tls:
  options:
    minVersion: "VersionTLS12"
    sniStrict: true
  stores:
    default:
#       clientAuth:
#         # in PEM format. each file can contain multiple CAs.
#         caFiles:
#           - /etc/traefik/achievernotifier.com.crt
#         clientAuthType: RequireAndVerifyClientCert
      defaultCertificate:
        certFile: /etc/traefik/cert/x509.pem
        keyFile: /etc/traefik/cert/crt.privatekey.pem
#   certificates:
#     - certFile: /etc/traefik/achievernotifier.com.crt
#       keyFile: /etc/traefik/achievernotifier.com.key
#       stores:
#         - default
#     - certFile: /etc/traefik/cert/cert.crt
#       keyFile: /etc/traefik/cert/csr.key
#       stores:
#         - default
#     - certFile: /etc/traefik/cert/intermediate.crt
#       keyFile: /etc/traefik/cert/csr.key
#       stores:
#         - default
#     - certFile: /etc/traefik/cert/root.crt
#       keyFile: /etc/traefik/cert/csr.key
#       stores:
#         - default
#     - certFile: /etc/traefik/cert/x509.crt
#       keyFile: /etc/traefik/cert/csr.key
#       stores:
#         - default
