providers:
  docker:
    network: reverse_proxy_network
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    httpClientTimeout: 300
    
api: {}

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

    
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@localhost.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

tls:
  certificates:
    - certFile: /etc/traefik/achievernotifier.com.crt
      keyFile: /etc/traefik/achievernotifier.com.key
