providers:
  docker:
    network: reverse_proxy_network
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    httpClientTimeout: 300
    
log:
  level: DEBUG
  
api:
  debug: true

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@localhost.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

tls:
#   options:
#     minVersion: "VersionTLS12"
#     sniStrict: true
  stores:
    default:
      clientAuth:
        # in PEM format. each file can contain multiple CAs.
        caFiles:
          - /etc/traefik/ca.pem
        clientAuthType: RequireAndVerifyClientCert
      defaultCertificate:
        certFile: /etc/traefik/cert/fullchain.pem
        keyFile: /etc/traefik/cert/privatekey.pem
#   certificates:
#     - certFile: /etc/traefik/cert.pem
#       keyFile: /etc/traefik/privatekey.key
#       stores:
#         - default
