providers:
  docker:
    network: reverse_proxy_network
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    httpClientTimeout: 300
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true

log:
  filePath: /var/log/traefik.log
  level: DEBUG
  
api:
  debug: true

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
