providers:
  docker:
    network: reverse_proxy_network
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    httpClientTimeout: 300
#   file:
#     directory: /etc/traefik/dynamic
#     watch: true

log:
  filePath: /var/log/traefik.log
  level: DEBUG
  
api:
  debug: true

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

tls:
  certificates:
    - certFile: /etc/traefik/cert/achievernotifier.com.cert
      keyFile: /etc/traefik/cert/achievernotifier.com.key
      stores:
        - default
  default:
    clientAuth:
      # in PEM format. each file can contain multiple CAs.
      caFiles:
        - /etc/traefik/cert/ca.pem
      clientAuthType: RequireAndVerifyClientCert
    defaultCertificate:
      certFile: /etc/traefik/cert/fullchain.pem
      keyFile: /etc/traefik/cert/privatekey.pem

# tls:
# #   options:
# #     minVersion: "VersionTLS12"
# #     sniStrict: true
#   certificates:
#     - certFile: "/etc/traefik/cert/fullchain.pem"
#       keyFile: "/etc/traefik/cert/privatekey.pem"
#       stores:
#         - default
#   stores:
#     default:
#       clientAuth:
#         # in PEM format. each file can contain multiple CAs.
#         caFiles:
#           - "/etc/traefik/cert/ca.pem"
#         clientAuthType: RequireAndVerifyClientCert
#       defaultCertificate:
#         certFile: "/etc/traefik/cert/fullchain.pem"
#         keyFile: "/etc/traefik/cert/privatekey.pem"
