providers:
  docker:
    network: reverse_proxy_network
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    httpClientTimeout: 300
    
log:
  level: DEBUG
  
api:
  debug: true

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

tls:
#   options:
#     minVersion: "VersionTLS12"
#     sniStrict: true
  certificates:
    - certFile: "/etc/traefik/cert/fullchain.pem"
      keyFile: "/etc/traefik/cert/privatekey.pem"
      stores:
        - default
  stores:
    default:
      clientAuth:
        # in PEM format. each file can contain multiple CAs.
        caFiles:
          - "/etc/traefik/cert/ca.pem"
        clientAuthType: RequireAndVerifyClientCert
      defaultCertificate:
        certFile: "/etc/traefik/cert/fullchain.pem"
        keyFile: "/etc/traefik/cert/privatekey.pem"
