providers:
  docker:
    network: reverse_proxy_network
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    httpClientTimeout: 300
    
log:
  filePath: "/var/log/traefik.log"
  level: DEBUG
  
api:
  dashboard: true
  debug: true

serversTransport:
  insecureSkipVerify: true

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@localhost.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
