# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    secret: '%env(APP_SECRET)%'
    handle_all_throwables: true
    http_method_override: false
    http_client:
        enabled: true
    php_errors:
        log: true
    serializer:
        enabled: true
        enable_annotations: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        enabled: true
        storage_factory_id: session.storage.factory.native
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
