security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'bcrypt'
        
    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: email
        refresh_provider:
            entity:
                class: App\Entity\User
                property: id
                
    role_hierarchy:
        ROLE_USER: [IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_ANONYMOUSLY, PUBLIC_ACCESS]
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_register:
            pattern: ^/api/v1/auth/register
            security: false
#         api_achievement_show:
#             pattern: ^/api/v1/achievement/list/[0-9a-z-]+/a/[0-9a-z-]+
#             stateless: true
#             security: false
        api_token_refresh:
            pattern: ^/api/v1/auth/token/refresh
            stateless: true
            provider: refresh_provider
            refresh_jwt: ~
        api_login:
              pattern: ^/api/v1/auth/login
              stateless: true
              json_login:
                  provider: entity_provider
                  username_path: email
                  password_path: password
                  check_path: /api/v1/auth/login #same as the route configured in config/routes.yaml
                  success_handler: lexik_jwt_authentication.handler.authentication_success
                  failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:   ^/api
            stateless: true
            provider: entity_provider
            entry_point: jwt
            user_checker: App\Security\UserChecker
            jwt:
                authenticator: api.custom_jwt_authenticator
            refresh_jwt:
                check_path: /api/auth/token/refresh
            logout:
                path: api_auth_logout

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: '^/api/v1/auth/(login|register|token/refresh)', roles: PUBLIC_ACCESS }
        - { route: 'api_achievement_list_achievement_show', roles: PUBLIC_ACCESS, methods: ['GET', 'PUT'] }
        - { path: '^/api', roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
